In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt



In [2]:
df = pd.read_csv("E:/data science/Singapore  Resale Flat Prices Predicting/cleaned_data.csv")
df

town         flat_type  block       street_name  floor_area_sqm  \
0       ANG MO KIO            1 ROOM  309.0  ANG MO KIO AVE 1            31.0   
1       ANG MO KIO            1 ROOM  309.0  ANG MO KIO AVE 1            31.0   
2       ANG MO KIO            1 ROOM  309.0  ANG MO KIO AVE 1            31.0   
3       ANG MO KIO            1 ROOM  309.0  ANG MO KIO AVE 1            31.0   
4       ANG MO KIO            3 ROOM  216.0  ANG MO KIO AVE 1            73.0   
...            ...               ...    ...               ...             ...   
917671      YISHUN         EXECUTIVE  614.0      YISHUN ST 61           142.0   
917672      YISHUN         EXECUTIVE  824.0      YISHUN ST 81           146.0   
917673      YISHUN         EXECUTIVE  826.0      YISHUN ST 81           146.0   
917674      YISHUN         EXECUTIVE  826.0      YISHUN ST 81           146.0   
917675      YISHUN  MULTI GENERATION  666.0      YISHUN AVE 4           164.0   

              flat_model  lease_commence_date  resale_price  remaining_lease  \
0               Improved                 1977        9000.0        68.000000   
1               Improved                 1977        6000.0        68.000000   
2               Improved                 1977        8000.0        68.000000   
3               Improved                 1977        6000.0        68.000000   
4         New Generation                 1976       47200.0        68.000000   
...                  ...                  ...           ...              ...   
917671         Apartment                 1987      800000.0        62.250000   
917672        Maisonette                 1987      935000.0        62.833333   
917673        Maisonette                 1988      908000.0        62.916667   
917674        Maisonette                 1988      800000.0        63.000000   
917675  Multi Generation                 1987      998000.0        62.916667   

        resale_year  resale_month  storey_lower_bound  storey_upper_bound  
0              1990             1                  10                  12  
1              1990             1                   4                   6  
2              1990             1                  10                  12  
3              1990             1                   7                   9  
4              1990             1                   4                   6  
...             ...           ...                 ...                 ...  
917671         2024             2                   7                   9  
917672         2024             2                   7                   9  
917673         2024             2                   4                   6  
917674         2024             2                   1                   3  
917675         2024             2                   4                   6  

[917676 rows x 13 columns]

In [3]:
#using encoding make a copy
df1=df.copy()

object_data_cols = [var for var in df.columns if df[var].dtype == 'object']
object_data_cols

['town', 'flat_type', 'street_name', 'flat_model']

In [4]:
#list unique street names
streets = df1['street_name'].unique()
# map the streets to povide input to ML model
streets_mapping = {street: idx + 1 for idx, street in enumerate(streets)}
streets_mapping

{'ANG MO KIO AVE 1': 1,
 'ANG MO KIO AVE 3': 2,
 'ANG MO KIO AVE 4': 3,
 'ANG MO KIO AVE 10': 4,
 'ANG MO KIO AVE 5': 5,
 'ANG MO KIO AVE 8': 6,
 'ANG MO KIO AVE 6': 7,
 'ANG MO KIO AVE 9': 8,
 'ANG MO KIO AVE 2': 9,
 'BEDOK RESERVOIR RD': 10,
 'BEDOK NTH ST 3': 11,
 'BEDOK STH RD': 12,
 'NEW UPP CHANGI RD': 13,
 'BEDOK NTH RD': 14,
 'BEDOK STH AVE 1': 15,
 'CHAI CHEE RD': 16,
 'CHAI CHEE DR': 17,
 'BEDOK NTH AVE 4': 18,
 'BEDOK STH AVE 3': 19,
 'BEDOK STH AVE 2': 20,
 'BEDOK NTH ST 2': 21,
 'BEDOK NTH ST 4': 22,
 'BEDOK NTH AVE 2': 23,
 'BEDOK NTH AVE 3': 24,
 'BEDOK NTH AVE 1': 25,
 'BEDOK NTH ST 1': 26,
 'CHAI CHEE ST': 27,
 'SIN MING RD': 28,
 'SHUNFU RD': 29,
 'BT BATOK ST 11': 30,
 'BT BATOK WEST AVE 8': 31,
 'BT BATOK WEST AVE 6': 32,
 'BT BATOK ST 21': 33,
 'BT BATOK EAST AVE 5': 34,
 'BT BATOK EAST AVE 4': 35,
 'HILLVIEW AVE': 36,
 'BT BATOK CTRL': 37,
 'BT BATOK ST 31': 38,
 'BT BATOK EAST AVE 3': 39,
 'TAMAN HO SWEE': 40,
 'TELOK BLANGAH CRES': 41,
 'BEO CRES': 42,
 'TELOK B

In [5]:
# alter the column with the mapped numbers
df1['street_name'] = df1['street_name'].map(streets_mapping)

# Display the DataFrame
df1.head(2)

town flat_type  block  street_name  floor_area_sqm flat_model  \
0  ANG MO KIO    1 ROOM  309.0            1            31.0   Improved   
1  ANG MO KIO    1 ROOM  309.0            1            31.0   Improved   

   lease_commence_date  resale_price  remaining_lease  resale_year  \
0                 1977        9000.0             68.0         1990   
1                 1977        6000.0             68.0         1990   

   resale_month  storey_lower_bound  storey_upper_bound  
0             1                  10                  12  
1             1                   4                   6

In [6]:
df1['flat_type'].unique()

array(['1 ROOM', '3 ROOM', '4 ROOM', '5 ROOM', '2 ROOM', 'EXECUTIVE',
       'MULTI GENERATION'], dtype=object)

In [7]:
category_mapping = {
    '1 ROOM': 1,
    '2 ROOM': 2,
    '3 ROOM': 3,
    '4 ROOM': 4,
    '5 ROOM': 5,
    'EXECUTIVE': 6,
    'MULTI GENERATION': 7
}

# alter the column with the mapped numbers
df1['flat_type'] =df1['flat_type'].map(category_mapping)

# Display the DataFrame
df1.head(2)

town  flat_type  block  street_name  floor_area_sqm flat_model  \
0  ANG MO KIO          1  309.0            1            31.0   Improved   
1  ANG MO KIO          1  309.0            1            31.0   Improved   

   lease_commence_date  resale_price  remaining_lease  resale_year  \
0                 1977        9000.0             68.0         1990   
1                 1977        6000.0             68.0         1990   

   resale_month  storey_lower_bound  storey_upper_bound  
0             1                  10                  12  
1             1                   4                   6

In [8]:
# Create a mapping of 'flat_model' values to numbers
flat_model_mapping = {
    'IMPROVED': 1,
    'NEW GENERATION': 2,
    'MODEL A': 3,
    'STANDARD': 4,
    'SIMPLIFIED': 5,
    'MODEL A-MAISONETTE': 6,
    'APARTMENT': 7,
    'MAISONETTE': 8,
    'TERRACE': 9,
    '2-ROOM': 10,
    'IMPROVED-MAISONETTE': 11,
    'MULTI GENERATION': 12,
    'PREMIUM APARTMENT': 13,
    'Improved': 14,
    'New Generation': 15,
    'Model A': 16,
    'Standard': 17,
    'Apartment': 18,
    'Simplified': 19,
    'Model A-Maisonette': 20,
    'Maisonette': 21,
    'Multi Generation': 22,
    'Adjoined flat': 23,
    'Premium Apartment': 24,
    'Terrace': 25,
    'Improved-Maisonette': 26,
    'Premium Maisonette': 27,
    '2-room': 28,
    'Model A2': 29,
    'DBSS': 30,
    'Type S1': 31,
    'Type S2': 32,
    'Premium Apartment Loft': 33,
    '3Gen': 34
}

# Map 'flat_model' values to numbers
df1['flat_model'] =df1['flat_model'].map(flat_model_mapping)

# Display the DataFrame
df1.head(3)

town  flat_type  block  street_name  floor_area_sqm  flat_model  \
0  ANG MO KIO          1  309.0            1            31.0          14   
1  ANG MO KIO          1  309.0            1            31.0          14   
2  ANG MO KIO          1  309.0            1            31.0          14   

   lease_commence_date  resale_price  remaining_lease  resale_year  \
0                 1977        9000.0             68.0         1990   
1                 1977        6000.0             68.0         1990   
2                 1977        8000.0             68.0         1990   

   resale_month  storey_lower_bound  storey_upper_bound  
0             1                  10                  12  
1             1                   4                   6  
2             1                  10                  12

In [9]:
# Create a mapping of 'town' values to numbers
town_mapping = {
    'ANG MO KIO': 1,
    'BEDOK': 2,
    'BISHAN': 3,
    'BUKIT BATOK': 4,
    'BUKIT MERAH': 5,
    'BUKIT TIMAH': 6,
    'CENTRAL AREA': 7,
    'CHOA CHU KANG': 8,
    'CLEMENTI': 9,
    'GEYLANG': 10,
    'HOUGANG': 11,
    'JURONG EAST': 12,
    'JURONG WEST': 13,
    'KALLANG/WHAMPOA': 14,
    'MARINE PARADE': 15,
    'QUEENSTOWN': 16,
    'SENGKANG': 17,
    'SERANGOON': 18,
    'TAMPINES': 19,
    'TOA PAYOH': 20,
    'WOODLANDS': 21,
    'YISHUN': 22,
    'LIM CHU KANG': 23,
    'SEMBAWANG': 24,
    'BUKIT PANJANG': 25,
    'PASIR RIS': 26,
    'PUNGGOL': 27
}

# Map 'town' values to numbers
df1['town'] = df1['town'].map(town_mapping)

# Display the DataFrame
df1.head(4)

town  flat_type  block  street_name  floor_area_sqm  flat_model  \
0     1          1  309.0            1            31.0          14   
1     1          1  309.0            1            31.0          14   
2     1          1  309.0            1            31.0          14   
3     1          1  309.0            1            31.0          14   

   lease_commence_date  resale_price  remaining_lease  resale_year  \
0                 1977        9000.0             68.0         1990   
1                 1977        6000.0             68.0         1990   
2                 1977        8000.0             68.0         1990   
3                 1977        6000.0             68.0         1990   

   resale_month  storey_lower_bound  storey_upper_bound  
0             1                  10                  12  
1             1                   4                   6  
2             1                  10                  12  
3             1                   7                   9

In [10]:
# save the processed data for the deployment
df1.to_csv('final.csv')

Spliting

In [11]:
# assign feature and target variable
X = df1.drop('resale_price', axis= 1)
y = df1['resale_price']
#splitting the data into training and testing sets with the ratio of 8:2
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=72)

In [12]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(734140, 12) (183536, 12) (734140,) (183536,)


Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled ,X_test_scaled

(array([[ 0.04450157, -0.01503475, -1.09608866, ...,  1.00263437,
         -0.55506942, -0.55813238],
        [-0.34035395, -0.01503475, -1.11132362, ...,  1.29506375,
          1.31433725,  1.31123237],
        [ 0.94249779,  1.03917853,  1.96613906, ...,  1.00263437,
          0.06806613,  0.0649892 ],
        ...,
        [ 1.45563848,  1.03917853, -0.19341705, ..., -0.16708316,
          1.31433725,  1.31123237],
        [ 0.30107192,  1.03917853, -1.07323621, ..., -1.0443713 ,
          1.31433725,  1.31123237],
        [-1.23835016, -0.01503475,  0.44264269, ...,  0.71020499,
         -0.55506942, -0.55813238]]),
 array([[ 0.04450157, -1.06924803, -1.11513236, ...,  1.00263437,
         -1.17820498, -1.18125396],
        [ 0.68592744, -0.01503475,  0.54928743, ...,  0.41777561,
          0.06806613,  0.0649892 ],
        [-0.72520947, -0.01503475,  0.45787765, ..., -0.75194192,
         -1.17820498, -1.18125396],
        ...,
        [ 0.68592744, -1.06924803, -0.72283204, ..., -

In [14]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [15]:
# Create and train the Decision Tree Regressor model
dt_regressor = DecisionTreeRegressor(max_depth=20, random_state=11)
dt_regressor.fit(X_train, y_train)

# Make predictions on the test set using Decision Tree model
y_pred_dt = dt_regressor.predict(X_test)

# Calculate Mean Absolute Error (MAE)
mae_dt = mean_absolute_error(y_test, y_pred_dt)

# Calculate Mean Squared Error (MSE)
mse_dt = mean_squared_error(y_test, y_pred_dt)

# Calculate Root Mean Squared Error (RMSE)
rmse_dt = np.sqrt(mse_dt)

# Calculate R-squared (R2) Score
r2_dt = r2_score(y_test, y_pred_dt)

print("Mean Absolute Error (MAE)    :", mae_dt)
print("Mean Squared Error (MSE)     :", mse_dt)
print("Root Mean Square Error (RMSE):", rmse_dt)
print("R-squared (R2) Score         :", r2_dt)

Mean Absolute Error (MAE)    : 18341.64592281376
Mean Squared Error (MSE)     : 776450553.8818742
Root Mean Square Error (RMSE): 27864.8623517482
R-squared (R2) Score         : 0.9727550501642148


In [18]:
dt_regressor

DecisionTreeRegressor(max_depth=20, random_state=11)

In [33]:
a={'town':15,'flat_type':3,'block':47.0,'street_name':162,'floor_area_sqm':65.0,'flat_model':14,'lease_commence_date':1975,'remaining_lease':68.0,'resale_year':2013,'resale_month':4,'storey_lower_bound':1,'storey_upper_bound':3}
a_df=pd.DataFrame(a,index=[0])
a_df

town  flat_type  block  street_name  floor_area_sqm  flat_model  \
0    15          3   47.0          162            65.0          14   

   lease_commence_date  remaining_lease  resale_year  resale_month  \
0                 1975             68.0         2013             4   

   storey_lower_bound  storey_upper_bound  
0                   1                   3

In [34]:
pre_pred = dt_regressor.predict(a_df)
pre_pred

array([406082.35294118])

In [19]:
# Saving the model
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(dt_regressor, file)